### ISSUE TITLE
s2Member KB Search: Not returning expected results

### ISSUE THREAD

**Issue by raamdev** [jaswsinc/alfred-workflows#1]
When I type `s2 s2member-list` in Alfred, the search results look like this:

![2015-04-03_12-36-35](https://cloud.githubusercontent.com/assets/53005/6985141/13cf0e0a-d9fe-11e4-8187-54cec2312f5f.png)

As you can see, only one result is related to the `[s2Member-List /]` shortcode (_"Can I display a member directory?"_).

I thought maybe it was because Google's index was out of date, so I searched s2Member.com to see the dates on the related articles:

![2015-04-03_12-36-52](https://cloud.githubusercontent.com/assets/53005/6985151/37f4b596-d9fe-11e4-8792-401c4a862046.png)

As you can see, there are articles going back almost a month (March 12th) containing "[s2Member-List /]" in their title--why don't these show up in Alfred? Is the Google API maybe not catching that term because it's surrounded by square brackets?

---

Another related question: How difficult would it be to use the s2Member KB search engine to retrieve results via Alfred? I'm asking because if we're going to be searching the KB frequently, it would help for us to be interfacing with the same search engine that powers the KB on s2Member.com, as a way for us to see how the results could be improved _and_ so that articles that were recently published show up in the results (i.e., we don't need to wait until Google indexes them).

**Comment by jaswsinc** [comment]
@raamdev writes...
> As you can see, only one result is related to the [s2Member-List /] shortcode ("Can I display a member directory?").

I noticed this also. Searching for `s2get` turns up nothing at all. I just indexed this yesterday, so it hasn't had much settling in time yet. I'll give it another few days and see if this improves.

Searching Google for `s2member-list` works as expected, so I don't think this has anything to do with `[]` brackets. It is either a bug in Google CSE, or it just takes time for Google to become wiser. Not really sure what else it could be yet.

---

@raamdev writes...
> How difficult would it be to use the s2Member KB search engine to retrieve results via Alfred?

Assuming that we have a good search engine, not difficult at all. However, improving search functionality in WPKBA is going to be time consuming. See: https://github.com/websharks/wp-kb-articles/issues/101

**Comment by jaswsinc** [comment]
@raamdev writes...
> it would help for us to be interfacing with the same search engine that powers the KB on s2Member.com

I agree. However, one thing to point out is that Alfred prioritizes the results that a Workflow returns in order to improve relevance. For instance, if you search for something and commonly choose a particular result, Alfred learns from this and prioritizes that result in the future.

That's great! However, it will also change the way results are returned by any search engine that we introduce as an Alfred Workflow. I'll see if there is a way to disable this. I haven't looked yet.

**Comment by raamdev** [comment]
> Alfred learns from this and prioritizes that result in the future.

Ah, yes, good point. I did not even think about that. If we can find a way to disable that functionality, that would be great. But even if we can't I suppose it's not that big of a deal. For support staff, having Alfred prioritize most frequently selected articles is actually a lot better, as we're more likely to reference the same articles over and over than to be looking for a very specific one.

**Comment by raamdev** [comment]
As of the new fulltext search APIs powered by WPKBA instead of by Google Custom Search, the results are exactly what I'd expect--woohoo! :-) Closing this issue.
