### ISSUE TITLE
s2Member Search: Long titles getting trimmed?

### ISSUE THREAD

**Issue by raamdev** [jaswsinc/alfred-workflows#2]
I noticed that when I searched for `auto-login` and then selected the KB Article titled _Why isn't the user automatically logged in after successful payment?_, it resulted in the following Markdown being inserted:

```text
[Why isn't the user automatically logged in after successful payment ...](http://s2member.com/kb-article/why-isnt-the-user-automatically-logged-in-after-successful-payment/)
```

Notice the ellipsis at the end: "Why isn't the user automatically logged in after a successful payment ...". Is there a maximum title length setting somewhere that is causing this, or a limitation somewhere?

**Comment by jaswsinc** [comment]
CSE for s2member.com: https://cse.google.com/cse/publicurl?cx=010747934993918679377:z4o9tflyaoa
CSE for zencache.com: https://cse.google.com/cse/publicurl?cx=010747934993918679377:mk9umip1h0q

It appears that the Google search engine is trimming these; i.e., it is stored this way in their index. The first 70 characters in a title are all they store it looks like.

**Comment by raamdev** [comment]
> It appears that the Google search engine is trimming these

Ah, I see. So I guess as long as we're using the Google search engine here, there's no way around this.

I'll go ahead and close this, but if you feel there's more worth investigating here, feel free to reopen this. :-)
