### ISSUE TITLE
HTML Entities in result titles

### ISSUE THREAD

**Issue by raamdev** [jaswsinc/alfred-workflows#3]
I noticed HTML entities appear to be showing up in the search results:

![2015-04-11_19-46-39](https://cloud.githubusercontent.com/assets/53005/7104117/8ed08b98-e097-11e4-9a30-250b1bd38c77.png)

**Comment by jaswsinc** [comment]
Ah. Thanks for catching that.

I just fixed this, along with some other tweaks/enhancements to the WPKBA JSON API. In addition, I improved my Alfred Workflows just a bit and added some new configuration options to the top of each script file that you can tweak.

_**Note:** The default sub-text in my workflows was changed from `url` to `snippet`. See screenshot of the `$config` options below. You can change it back to `url` if you prefer._

![](https://www.filepicker.io/api/file/UEjBfi4dRYawWJLSkVgO#.png)
![](https://www.filepicker.io/api/file/gF93QbhTviYtrNwExUIA#.png)

---

The snippets that WPKBA pulls for each result are not bad, but there is room for improvement. I'll be working to enhance the snippet generation in WPKBA as we move forward. Those changes will show up in the Alfred Workflow automatically though.

**Comment by jaswsinc** [comment]
Along with the latest changes, I also character support in Markdown links. Making it possible to inject a link that contains a title with `[` or `]` in it. Escaping is performed automatically now.

```text
[\[s2Drip /\] Shortcode](http://s2member.com/kb-article/s2drip-shortcode/)
```

[\[s2Drip /\] Shortcode](http://s2member.com/kb-article/s2drip-shortcode/)

**Comment by raamdev** [comment]
@jaswsinc Perfect! I just updated and it looks great. Thanks! :-)
